- name: Get Fabric devices info from Cisco Catalyst Center
  hosts: localhost
  connection: local
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Get Fabric devices info from Cisco Catalyst Center
      cisco.dnac.fabric_devices_info_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - fabric_devices:
              - ip_address: ["204.1.2.2","204.1.2.3"]
                # hostname: ["TB1-DM-Transit.solutionsanity.com"]
                # serial_number: ["FJC2335S09F"]
                # device_role: ["ACCESS"]
                # device_type: ["Cisco Catalyst 9130AXE Unified Access Point"]
                # site_hierarchy: ["Global/USA/New York/NY_BLD1", "Global/USA/New York/NY_BLD1/FLOOR1"]
                timeout: 12
                retries: 4
                interval: 10
                # output_file_path: "/Users/Priya/Downloads/INFO"
                requested_info: 
                  - fabric_info
                  - handoff_info
                  - onboarding_info
                  - connected_devices_info
                  - device_health_info
                  - device_issues_info