- name: Get Fabric devices info from Cisco Catalyst Center
  hosts: localhost
  connection: local
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Get Fabric devices info from Cisco Catalyst Center
      cisco.dnac.fabric_devices_info_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - fabric_devices:
              # - site_hierarchy: ["Global/USA/New York/BLDNYC"]
              - ip_address: ["204.1.1.37"]
              # - hostname: ["AP0CD0.F894.0C44","AP0CD0.F894.0C44"]
              # - serial_number: ["KWC22440QJ2"]
                # device_role: ["ACCESS"]
                # device_type: ["Cisco Catalyst 9130AXE Unified Access Point"]
                requested_info: 
                   - device_issues_info
                # file_info:
                #   file_path: /Users/priyadharshini/Downloads/device_pireeeeya
                #   file_format: yaml
                #   file_mode: a
                #   timestamp: True
