# ---
# - name: Get IP pool reservations
#   hosts: dnac_servers
#   vars_files:
#     - credentials.yml
#   gather_facts: false
#   connection: local
#   tasks:
#     - name: Get Reservations with pagination
#       cisco.dnac.reserve_ip_subpool_info:
#         dnac_host: "{{ dnac_host }}"
#         dnac_username: "{{ dnac_username }}"
#         dnac_password: "{{ dnac_password }}"
#         dnac_verify: "{{ dnac_verify }}"
#         dnac_port: "{{ dnac_port }}"
#         dnac_version: "{{ dnac_version }}"
#         dnac_debug: "{{ dnac_debug }}"
#         siteId: "b409e651-a8b3-4cc5-91ff-a668e61c4d65"
#         offset: 1      # Must be >= 1
#         limit: 25      # Must be provided with offset
#       register: ip_pools


---
- name: Get IP pool reservations
  hosts: dnac_servers
  # connection: local
  vars_files:
    - "credentials.yml"

  connection: local
  tasks:
    - name: Get Reservations with pagination
      cisco.dnac.reserve_ip_subpool_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        siteId: "b409e651-a8b3-4cc5-91ff-a668e61c4d65"
        offset: 1      # Must be >= 1
        limit: 25      # Must be provided with offset
      register: ip_pool

 