- name: Get all anycast gateways with pagination
  hosts: dnac_servers
  connection: local
  vars_files:
    - credentials.yml
  tasks:
    - name: Initialize results
      set_fact:
        all_gateways: []
        current_offset: 0
        batch_size: 500
        has_more: true

    - name: Get gateways in batches
      block:
        - name: Get batch of gateways
          cisco.dnac.sda_anycast_gateways_info:
            dnac_host: "{{ dnac_host }}"
            dnac_username: "{{ dnac_username }}"
            dnac_password: "{{ dnac_password }}"
            dnac_verify: "{{ dnac_verify }}"
            dnac_port: "{{ dnac_port }}"
            dnac_version: "{{ dnac_version }}"
            dnac_debug: "{{ dnac_debug }}"
            offset: "{{ current_offset }}"
            limit: "{{ batch_size }}"
          register: gateway_batch

        - name: Append to results
          set_fact:
            all_gateways: "{{ all_gateways + gateway_batch.dnac_response.response }}"

        - name: Check if more records exist
          set_fact:
            has_more: "{{ gateway_batch.dnac_response.response | length == batch_size }}"
            current_offset: "{{ current_offset + batch_size }}"

      # when: has_more | bool
      # loop: "{{ range(0, 100) }}"  # Max 100 iterations (50,000 records)
      # loop_control:
      #   loop_var: iteration